create table users (
    id bigint generated by default as identity primary key,
    username varchar(32) not null unique,
    password varchar(500) not null,
    enabled boolean not null,
    created_at timestamp not null,
    created_by varchar(32),
    updated_at timestamp not null,
    updated_by varchar(32),
    version int not null
);

create table authorities (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    authority varchar(50) not null,
    created_at timestamp not null,
    created_by varchar(32),
    updated_at timestamp not null,
    updated_by varchar(32),
    version int not null,
    unique (user_id, authority)
);
