create table todos (
    id bigint generated by default as identity primary key,
    text varchar(2048) not null,
    created_at timestamp not null,
    created_by varchar(32),
    updated_at timestamp not null,
    updated_by varchar(32),
    version int not null
);

create table file_info (
    id bigint generated by default as identity primary key,
    file_name varchar(255) not null,
    content_type varchar(255),
    original_content_type varchar(255),
    length int not null,
    hash_value varchar(64) not null,
    created_at timestamp not null,
    created_by varchar(32),
    updated_at timestamp not null,
    updated_by varchar(32),
    version int not null
);

create table file_data (
    id bigint generated by default as identity primary key,
    file_info_id bigint not null unique references file_info(id),
    data bytea not null,
    created_at timestamp not null,
    created_by varchar(32),
    updated_at timestamp not null,
    updated_by varchar(32),
    version int not null
);
