spring:
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
