spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jnotesdb
    username: jnotes
    password: jnotes
  data:
    redis:
      host: localhost
      port: 6379

logging:
  file:
    name: ${user.home}/logs/jnotes/app.log
  level:
    web: DEBUG
    sql: DEBUG
    "[jp.gr.java_conf.stardiopside.jnotes]": DEBUG
